### ISSUE TITLE
Add a license to the repo and footer of site

### ISSUE THREAD

**Issue by asset-web** [lifen-joy/Persona-Shuffle#12]
If at times this repository will be public adding a license agreement would be wise.

Open source, see: 
- https://choosealicense.com/

Examples of closed source

- https://en.wikipedia.org/wiki/Proprietary_software
- https://www.oreilly.com/library/view/understanding-open-source/0596005814/ch05.html

**Comment by lifen-joy** [comment]
Info from https://creativecommons.org/choose/

Our license 
https://creativecommons.org/licenses/by-nc-sa/4.0/

<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.

**Comment by lifen-joy** [comment]
Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)
This is a human-readable summary of (and not a substitute for) the license. Disclaimer.
You are free to:
Share — copy and redistribute the material in any medium or format
Adapt — remix, transform, and build upon the material
The licensor cannot revoke these freedoms as long as you follow the license terms.
Under the following terms:
Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

NonCommercial — You may not use the material for commercial purposes.

ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.
Notices:
You do not have to comply with the license for elements of the material in the public domain or where your use is permitted by an applicable exception or limitation.
No warranties are given. The license may not give you all of the permissions necessary for your intended use. For example, other rights such as publicity, privacy, or moral rights may limit how you use the material.

**Comment by lifen-joy** [comment]
Long legal code 
https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode
