### ISSUE TITLE
Review image categorisation

### ISSUE THREAD

**Issue by asset-web** [lifen-joy/Persona-Shuffle#14]
Consider if you want an ambiguous third category or not.
Alternatively review some borderline category b images.

NB: Any changes to the total count of images should be reflected here too: https://github.com/lifen-joy/Persona-Shuffle/blob/master/js/image-shuffle.js#L4

Also image naming should be consecutive numbers, to work with the current codebase.

**Comment by lifen-joy** [comment]
Made group be clearer in difference
